// Future<File> getImage() async {
//   final ImagePicker _picker = ImagePicker();
// // Pick an image
//   final XFile? image = await _picker.pickImage(source: ImageSource.gallery);
// //TO convert Xfile into file
//   File file = File(image!.path);
// //print(‘Image picked’);
//   return file;
// }
// var formData = FormData.fromMap({
//         'file': await MultipartFile.fromFile(empFace.path, filename: empCode),
//       });

//       final response = await Dio().post(
//         'your Api url',
//         data: formData,
//       );

//       headers: {
//     'Content-Type': 'multipart/form-data'
//   },
  var arabic={
    "Park your car":"احجز سيارتك",
    "Forgot Password":"هل نسيت كلمة المرور",
    "Enter your Email should we use to reset your password":"قم بادخال ايميلك لاعادة كلمة المرور",
    "Send code":"ارسل الرمز",
    "Code Sent !":"لقد تم ارسال الكود الخاص بك",
    "Code has been sent to Email":"تم ارسال الكود الى ايميلك",
    "Verify":"تاكيد",
    "Didn't receive it ? Resend":"ألم تستلمها؟ إعادة إرسال",
    "Reset password":"إعادة تعيين كلمة المرور",
    "Enter New Password":"أدخل كلمة مرور جديدة",
    "Confirm New Password":"تأكيد كلمة المرور الجديدة",
    "Confirm":"يتأكد",
    "The password has been reset successfully":"تم إعادة تعيين كلمة المرور بنجاح",
    "My car":"سيارتك",
    "Enter your car Details":"أدخل تفاصيل سيارتك",
    "Car Number":"رقم سيارتك",
    "Enter your car number":"أدخل رقم سيارتك",
    "Car name":"اسم سيارتك",
    "Enter your car name":"أدخل اسم سيارتك",
    "Car color":"لون سيارتك",
    "Choose the color of your car":"اختر لون سيارتك",
    "Add vehicle":"أضف مركبة",
    "select preferred space":"حدد المساحة المفضلة",
    "Entry":"ادخل",
    "4 slots Free":"4 فتحات مجانية",
    "BOOK":"لحجز",
    "Reservation information":"معلومات الحجز",
    "Place and code":"المكان والرمز",
    "Your place P- 02 and your code is 9516":"مكانك P- 02 ورمزك هو 9516",
    "Description of the place":"وصف المكان",
    "P - 02 is the Second place to the right of the entrance":"P - 02 هو المكان الثاني على يمين المدخل",
    "Information of our car":"معلومات سيارتنا",
    "Red | Mercedes":"أحمر | مرسيدس",
    "OK":"تاكيد",
    "Parking Timer":"مؤقت وقوف السيارات",
    "Your place is P- 02":"مكانك  P- 02",
    "Finish":"انهاء",
    "payment":"الدفع",
    "choose payment method":"اختر وسيلة الدفع",
    "Vodafone cash":"فودافون كاش",
    "Credit Card":"فيزة كارت",
    "Total payment":"المبلغ الإجمالي",
    "1 Hour":"ساعة",
    "Pay Now":"ادفع الان",
    "Payment Succesful !":"تم الدفع بنجاح",
    "Your Exit code is:":"كود الخروج الخاص بك هو:",
    "Notification":"اشعارات",
    "New":"الجديد",
    "P - 02 is the Second place to the right of the entrance and your place code is : 8894":"P - 02 هو المكان الثاني على يمين المدخل ورمز مكانك هو: 8894",
    "the oldest":"القديم",
    "P - 12 is the Sixth place to the left of the entrance and your place code is : 1536":"P - 12 هو المكان السادس على يسار المدخل ورمز مكانك هو: 1536",
    "P - 01 is the First place to the right of the entrance and your place code is : 9764":"P - 01 هو المكان الأول على يمين المدخل ورمز مكانك هو: 9764",
    "P - 05 is the Fifth place to the right of the entrance and your place code is : 9164":"P - 05 هو المكان الخامس على يمين المدخل ورمز مكانك هو: 9164",
    "Settings":"الاعدادات",
    "Your profile":"ملفك الشخصي",
    "Sign out":"الخروج",
    "Create your Account":"أنشئ حسابك",
    "Your name":"اسمك",
    "Enter your email":"ادخل ايميلك",
    "Enter your password":"ادخل كلمة المرور الخاص بك",
    "Repeat your password":"أعد كتابة رقمك السري",
    "Create account":"إنشاء حساب",
    "Verify your email":"قم بتأكيد بريدك الألكتروني",
    "Sent code":"الكود المرسل",
    "Email has successfully created":"تم إنشاء البريد الإلكتروني بنجاح",
  };
  var english={
    "Park your car":"Park your car",
    "Forgot Password":"Forgot Password",
    "Enter your Email should we use to reset your password":"Enter your Email should we use to reset your password",
    "Send code":"Send code",
    "Code Sent !":"Code Sent !",
    "Code has been sent to Email":"Code has been sent to Email",
    "Verify":"Verify",
    "Didn't receive it ? Resend":"Didn't receive it ? Resend",
    "Reset password":"Reset password",
    "Enter New Password":"Enter New Password",
    "Confirm New Password":"Confirm New Password",
    "Confirm":"Confirm",
    "The password has been reset successfully":"The password has been reset successfully",
    "My car":"My car",
    "Enter your car Details":"Enter your car Details",
    "Car Number":"Car Number",
    "Enter your car number":"Enter your car number",
    "Car name":"Car name",
    "Enter your car name":"Enter your car name",
    "Car color":"Car color",
    "Choose the color of your car":"Choose the color of your car",
    "Add vehicle":"Add vehicle",
    "select preferred space":"select preferred space",
    "Entry":"Entry",
    "4 slots Free":"4 slots Free",
    "BOOK":"BOOK",
    "Reservation information":"Reservation information",
    "Place and code":"Place and code",
    "Your place P- 02 and your code is 9516":"Your place P- 02 and your code is 9516",
    "Description of the place":"Description of the place",
    "P - 02 is the Second place to the right of the entrance":"P - 02 is the Second place to the right of the entrance",
    "Information of our car":"Information of our car",
    "Red | Mercedes":"Red | Mercedes",
    "OK":"OK",
    "Parking Timer":"Parking Timer",
    "Your place is P- 02":"Your place is P- 02",
    "Finish":"Finish",
    "payment":"payment",
    "choose payment method":"choose payment method",
    "Vodafone cash":"Vodafone cash",
    "Credit Card":"Credit Card",
    "Total payment":"Total payment",
    "1 Hour":"1 Hour",
    "Pay Now":"Pay Now",
    "Payment Succesful !":"Payment Succesful !",
    "Your Exit code is:":"Your Exit code is:",
    "Notification":"Notification",
    "New":"New",
    "P - 02 is the Second place to the right of the entrance and your place code is : 8894":"P - 02 is the Second place to the right of the entrance and your place code is : 8894",
    "the oldest":"the oldest",
    "P - 12 is the Sixth place to the left of the entrance and your place code is : 1536":"P - 12 is the Sixth place to the left of the entrance and your place code is : 1536",
    "P - 01 is the First place to the right of the entrance and your place code is : 9764":"P - 01 is the First place to the right of the entrance and your place code is : 9764",
    "P - 05 is the Fifth place to the right of the entrance and your place code is : 9164":"P - 05 is the Fifth place to the right of the entrance and your place code is : 9164",
    "Settings":"Settings",
    "Your profile":"Your profile",
    "Sign out":"Sign out",
    "Create your Account":"Create your Account",
    "Your name":"Your name",
    "Enter your email":"Enter your email",
    "Enter your password":"Enter your password",
    "Repeat your password":"Repeat your password", 
    "Create account":"Create account",
    "Verify your email":"Verify your email",
    "Sent code":"Sent code",
    "Email has successfully created":"Email has successfully created",
  };
